# slang_detector.py
import string
# 🔷 Extended Slang Dictionary
SLANG_DICT = {
    "aesthetic": "visually pleasing or a specific style",
    "ate": "did something perfectly",
    "aura": "cool level max",
    "left no crumbs": "did something perfectly",
    "based": "being yourself, not caring what others think",
    "basic": "unoriginal, mainstream",
    "bet": "yes, okay, or I agree",
    "bffr": "be for real",
    "big yikes": "extreme cringe or embarrassment",
    "bop": "a really good song",
    "brainrot": "mindless internet content",
    "brat": "rebellious, unapologetic energy",
    "bruh": "expression of disbelief",
    "bussin": "extremely good",
    "camp": "intentionally exaggerated style",
    "cap": "lie",
    "no cap": "truth",
    "catch hands": "start a fight",
    "caught in 4k": "caught with proof",
    "ceo": "best at something",
    "chad": "confident alpha male",
    "cheugy": "outdated or uncool",
    "clout": "fame or influence",
    "coded": "having certain traits",
    "cook": "do something well",
    "copium": "denying reality",
    "crash out": "lose control",
    "cringe": "awkward or embarrassing",
    "dank": "high quality meme",
    "deadass": "completely serious",
    "delulu": "delusional",
    "doing the most": "overreacting",
    "drip": "stylish outfit",
    "dub": "win",
    "dupe": "cheap alternative",
    "era": "phase of life",
    "extra": "over dramatic",
    "fanum tax": "stealing food",
    "feral": "wild behavior",
    "finesse": "get something cleverly",
    "finna": "going to",
    "fire": "really good",
    "fit check": "showing outfit",
    "flex": "show off",
    "flop": "failure",
    "fold": "give up",
    "gagged": "shocked",
    "gas": "hype up",
    "gatekeep": "hide information",
    "ghost": "ignore completely",
    "girlboss": "confident woman",
    "glaze": "overpraise",
    "glow up": "big improvement",
    "goat": "greatest of all time",
    "goated": "the best",
    "gyat": "expression of surprise",
    "heather": "perfect person",
    "highkey": "very obvious",
    "him": "top performer",
    "hits different": "feels unique",
    "ick": "sudden turn off",
    "lol": "laughing hard",
    "it girl": "trending person",
    "iykyk": "if you know you know",
    "jumpscare": "sudden surprise",
    "let him cook": "let him do his thing",
    "lit": "exciting",
    "lore": "backstory",
    "lowkey": "slightly or secretly",
    "l": "loss",
    "looksmaxxing": "improving appearance",
    "main character": "center of attention",
    "mid": "average",
    "mog": "more attractive",
    "moots": "mutual followers",
    "mother": "iconic woman",
    "naur": "no",
    "npc": "no independent thinking",
    "oof": "minor sympathy",
    "oomf": "one of my followers",
    "opp": "enemy",
    "out of pocket": "inappropriate",
    "periodt": "end of discussion",
    "pick me": "attention seeker",
    "pookie": "cute nickname",
    "pop off": "perform well suddenly",
    "pressed": "angry",
    "ratio": "more likes on reply",
    "rent free": "constantly thinking",
    "rizz": "charisma",
    "salty": "bitter",
    "secure the bag": "make money",
    "shook": "shocked",
    "sigma": "independent male",
    "simp": "overly devoted",
    "situationship": "undefined relationship",
    "skibidi": "random nonsense",
    "slaps": "really good",
    "slay": "do great",
    "snatched": "looking very good",
    "soft launch": "hint relationship",
    "spill the tea": "share gossip",
    "stan": "obsessive fan",
    "sus": "suspicious",
    "tea": "gossip",
    "touch grass": "go outside",
    "tweaking": "acting crazy",
    "unalive": "kill or die",
    "valid": "acceptable",
    "vibe check": "check mood",
    "w": "win",
    "wig snatched": "very impressed",
    "woke": "socially aware",
    "yap": "talk too much",
    "yeet": "throw forcefully",
    "zesty": "flamboyant"
}


def detect_slang(text):
    # Remove punctuation to catch words like "tea!" 
    text_clean = text.translate(str.maketrans('', '', string.punctuation))
    words = text_clean.split()
    
    detected = {}
    for w in words:
        lw = w.lower()
        if lw in SLANG_DICT:
            detected[w] = SLANG_DICT[lw]
    return detected